---

- name: Install Homebrew Cask Applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - java

- name: Install Homebrew Applications
  homebrew: name={{item}} state=present
  with_items:
    - groovy

- name: Set Environnement Variable for Groovy
  lineinfile: dest=~/.zshrc regexp='export GROOVY_HOME=/usr/local/opt/groovy/libexec' insertafter='^# User configuration' line='export GROOVY_HOME=/usr/local/opt/groovy/libexec' state=present

# - include: jenkins.yml
