---

- name: Install Java
  homebrew_cask: name={{item}} state=present
  with_items:
    - java
    - firefox

- name: Install Jenkins
  homebrew: name={{item}} state=present
  with_items:
    - jenkins

- name: Stop Jenkins
  command: launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.jenkins.plist

- name: Configuring jenkins LaunchAgent
  template: >
    src=homebrew-mxcl-jenkins-plist.j2
    dest=~/Library/LaunchAgents/homebrew.mxcl.jenkins.plist
  with_items: jenkins_var

- name: Create symlink to jenkins LaunchAgent
  file: src={{ item }} dest=~/Library/LaunchAgents/{{ item | basename}} state=link force=yes
  with_fileglob:
        - /usr/local/opt/jenkins/*.plist

- name: Start Jenkins
  command: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.jenkins.plist

- name: Wait Jenkins is started
  command: sleep 10

- name: Install Plugins
  # command: jenkins-cli -s "http://{{ jenkins_var.httpListenAddress }}:{{ jenkins_var.httpPort }}/" install-plugin {{ item }}
  command: jenkins-cli -s "http://0.0.0.0:8888/" install-plugin {{ item }}
  with_items:
    - additional-identities-plugin
    - android-emulator

- name: Restart Jenkins
  command: jenkins-cli -s "http://0.0.0.0:8888/" restart

# # Make sure Jenkins starts, then configure Jenkins.
# - name: Ensure Jenkins is started and runs on startup.
#   service: name=jenkins state=started enabled=yes
#
# - name: Wait for Jenkins to start up before proceeding.
#   shell: "curl -D - --silent http://{{ jenkins_hostname }}:8080{{ jenkins_url_prefix }}/cli/"
#   register: result
#   until: (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
#   retries: "5"
#   delay: "60"
#   changed_when: false
