---

- name: Install Java
  homebrew_cask: name={{item}} state=present
  with_items:
    - java

- name: Install Jenkins
  homebrew: name={{item}} state=present
  with_items:
    - jenkins

- name: Stop Jenkins
  command: launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.jenkins.plist

- name: Configuring jenkins LaunchAgent
  template: >
    src=homebrew-mxcl-jenkins-plist.j2
    dest=~/Library/LaunchAgents/homebrew.mxcl.jenkins.plist
  with_items: jenkins_var

- name: Create symlink to jenkins LaunchAgent
  file: src={{ item }} dest=~/Library/LaunchAgents/{{ item | basename}} state=link force=yes
  with_fileglob:
        - /usr/local/opt/jenkins/*.plist

- name: Start Jenkins
  command: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.jenkins.plist

- name: Wait Jenkins is started
  command: sleep 10

- name: Install Plugins
  # command: jenkins-cli -s "http://{{ jenkins_var.httpListenAddress }}:{{ jenkins_var.httpPort }}/" install-plugin {{ item }}
  command: jenkins-cli -s "http://0.0.0.0:8888/" install-plugin {{ item }}
  with_items:
    - additional-identities-plugin
    - android-emulator

- name: Get latest Jenkins update file
  get_url: url=http://updates.jenkins-ci.org/update-center.json dest=~/.jenkins/updates_jenkins.json thirsty=yes mode=0440
  register: jenkins_updates
  tags:
    - jenkins
    - jenkins-update

- name: Update-center Jenkins
  shell: "cat ~/.jenkinsjenkins/updates_jenkins.json | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- http://0.0.0.0:8888/updateCenter/byId/default/postBack"
  when: jenkins_updates.changed
  tags:
    - jenkins
    - jenkins-update

- name: Restart Jenkins
  command: jenkins-cli -s "http://0.0.0.0:8888/" restart

- name: Wait Jenkins is started
  command: sleep 10

- name: List Jenkins plugins
  shell: "jenkins-cli http://0.0.0.0:8888 list-plugins | cut -f 1 -d ' '"
  when: jenkins.plugins is defined
  register: plugins_installed
  tags:
    - jenkins
    - jenkins-update

- name: Install/update Jenkins plugins
  command: jenkins-cli -s http://0.0.0.0:8888 install-plugin {{ item }}
  when: "plugins_installed.changed and plugins_installed.stdout.find('{{ item }}') == -1"
  with_items: jenkins.plugins
  tags:
    - jenkins
    - jenkins-update

- name: Restart Jenkins
  command: jenkins-cli -s "http://0.0.0.0:8888/" restart

- name: Wait Jenkins is started
  command: sleep 10

- name: List Jenkins plugins to be updated
  shell: jenkins-cli -s http://l0.0.0.0:8888 list-plugins | grep ')$' | cut -f 1 -d ' ' | sed ':a;N;$!ba;s/\n/ /g'
  register: plugins_updates
  tags:
    - jenkins
    - jenkins-update

- name: Update Jenkins plugins
  command: jenkins-cli -s http://0.0.0.0:8888 install-plugin {{ plugins_updates.stdout }}
  when: plugins_updates.stdout != ''
  tags:
    - jenkins
    - jenkins-update

- name: Restart Jenkins
  command: jenkins-cli -s "http://0.0.0.0:8888/" restart

# # Make sure Jenkins starts, then configure Jenkins.
# - name: Ensure Jenkins is started and runs on startup.
#   service: name=jenkins state=started enabled=yes
#
# - name: Wait for Jenkins to start up before proceeding.
#   shell: "curl -D - --silent http://{{ jenkins_hostname }}:8080{{ jenkins_url_prefix }}/cli/"
#   register: result
#   until: (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
#   retries: "5"
#   delay: "60"
#   changed_when: false
