---

- hosts: 127.0.0.1
  connection: local

  roles:
    - profile-all
    - profile-tester-ios

  vars:
    - users:
      - name: Admin
        username: admin
        group: staff
        oh_my_zsh:
          theme: robbyrussell
          plugins: git node brew ruby
    - osx_defaults_present:
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'orientation'
        type: string
        value: bottom
        
    - dock_icons:
      - Google Chrome
      - iTerm
      - Atom
      - Sublime Text 2
      - XCode

    - dock_icons_to_delete:
      - Launchpad
      - Mail
      - Contacts
      - Calendar
      - Notes
      - Reminders
      - Maps
      - Photos
      - Messages
      - FaceTime
      - Pages
      - Numbers
      - Keynote
      - iTunes
      - iBooks
      - App Store
