---

- name: Install Node & Npm
  homebrew: {{item}} state=present
  with_items:
    - node
    - npm

- name: Install N for node
  npm: name=n global=true

- name: Install PM2 - Process Manager for Node.js
  npm: name={{item}} global=true
  with_items:
    - pm2
    - node-inspector
    - pm2-web

- name: Run PM2
  command: /usr/local/bin/pm2 start /usr/local/bin/pm2-web

#Check access to http://localhost:9000

- name: Install NPM Package
  npm: name={{item}} global=true
  with_items:
    - bower
