---
galaxy_info:
  author: D-Incubator
  description: Ansible profile role for all users
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - dincubator.oh-my-zsh
  - geerlingguy.jenkins
