---

- name: install general applications with Cask
  homebrew_cask: name={{item}} state=present
  with_items:
    - atom
    - iterm2
    - google-chrome

- name: install general applications with brew
  homebrew: name={{item}} state=present
  with_items:
    - wget

- name: Update git config url
  shell: git config --global url."https://".insteadOf git://

- osx_defaults: domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  with_items: osx_defaults_present

- osx_defaults: domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=absent
  with_items: osx_defaults_absent
