---
- stat: path=/Applications/Xcode.app
  register: xcode_app

- include: xcode.yml
  when: not xcode_app.stat.exists

- name: Agreed Xcode License
  shell: xcodebuild -license
  become: yes
  become_method: sudo

- name: Install Ruby Gem
  gem: name={{item}} state=latest
  with_items:
    - xcpretty
    - cocoapods
    - calabash-cucumber

- name: Create Provisioning Profiles folder
  file: path="~/MobileDevice/Provisioning Profiles" state=directory mode=0755

- name: Install Homebrew application
  homebrew: name={{ item }} state=present
  with_items:
    - ios-webkit-debug-proxy
    - lcov

- name: Install Homebrew Cask application
  homebrew_cask: name={{ item }} state=present
  with_items:
    - oclint

# - include: jenkins.yml
